## **Numpy Assignment**

Theory Questions :

1)  Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

Ans)Numpy is used to perform so many mathmatical operations which are used to analyse the data to find what kind of data is there and
this analysis is helpful to select the perfect model to train the data.
As Numpy is made by using c It is fast in performing the mathematical operations and helps to do large calculations and operations in algebra,
matrix operations etc  

2)Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

Ans) np.mean is used to calculate only the mean of the elements in the array by sum of elements to the number of elements in the array.
where as the np.average takes two inputs if only the array is given then it gives the mean of the array if the weighted array is also given then it will follows weighted Mean by using the two arrays.

3) Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

Ans) we can reverse the array by using the slicing and flip concepts.

In [ ]:
import numpy as np
arr1d= np.array([1,2,3,4,5])
print (arr1d[::-1])
arr2d=np.array([[2,3,4],[4,6,7],[6,7,8]])
print (arr2d[::-1])
np.flip(arr1d)
np.flip(arr2d)

[5 4 3 2 1]
[[6 7 8]
 [4 6 7]
 [2 3 4]]


array([[8, 7, 6],
       [7, 6, 4],
       [4, 3, 2]])

4) How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

Ans) Arrays are mainly used to store same type of datatypes in the array. because of this reason all the homogenous elements of the array are stored side by side. so if we call the elements it will come fast compare with the list because list contains different types of datatypes where each element will store in different locations which increases the memory and also the time to retrieve.  

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans) Ndarrays are used to store the homogenous data and the size is fixed at the time of creation, it is used to fast retrival of the elements and it also saves the memeory as the elements are side by side. It is also used to perform the mathematical operations like algebra, matrix operations etc...

Lists are used to store heterogenous data where it can increase the size when it is requried, it is slow compare to array as the elements are in different locations. It is not suitable for all mathematical operations.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans) Numpy arrays are mainly used when we requrie memory efficiency , used for mathematical operations, Speed .

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

Ans) These two are used to stack the array elements in the horizonatal or vertical stacks based on the commands.

In [ ]:
a= np.array([1,2,3,4])
b=np.array([5,9,5,3])
c=np.vstack((a,b))
c
d= np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 9, 5, 3])

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

Ans) Both them are used to flip the

In [ ]:
flip= np.array([[2,3,5,6],[5,3,2,1]])
e= np.fliplr(flip)
print(e)
f= np.flipud(flip)
print(f)

[[6 5 3 2]
 [1 2 3 5]]
[[5 3 2 1]
 [2 3 5 6]]


9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans) This is similar to split method which handels the uneven splits. it first tries to divides the array elements evenly by the given number if it is not happened then it will keep the remaining elements in the next sub array.

In [ ]:
arr = np.arange(6)
result = np.array_split(arr, 2)
result

[array([0, 1, 2]), array([3, 4, 5])]

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

Ans) Both are used to perform the operations fastly where vectorization performs operations element by element and broadcasting performs by expanding the matrices.

Practical Questions

In [ ]:
"1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns"

t=np.random.randint(1,100,(3,3))
print(t)
print(t.T)

[[96 62 27]
 [17 12 27]
 [43 87 22]]
[[96 17 43]
 [62 12 87]
 [27 27 22]]


In [ ]:
"2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array."
n=np.arange(10)
n.reshape(2,5)
n.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
"3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array."
f=np.random.rand(4,4)
np.pad(f,1)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.55759251, 0.9590636 , 0.71952978, 0.24289794,
        0.        ],
       [0.        , 0.76627775, 0.7291927 , 0.47282754, 0.06964111,
        0.        ],
       [0.        , 0.48344665, 0.38253432, 0.26831811, 0.23722793,
        0.        ],
       [0.        , 0.48425759, 0.804066  , 0.07846739, 0.50032839,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
"4. Using NumPy, create an array of integers from 10 to 60 with a step of 5."
arr1=np.arange(10,60,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [ ]:
'''5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.'''
Str=np.array(['python','numpy','pandas'])
np.char.upper(Str)
np.char.lower(Str)
np.char.title(Str)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [ ]:
'''6. Generate a NumPy array of words. Insert a space between each character of every word in the array'''
arr=np.array(['pw','skills','online','class'])
np.char.join(' ',arr)

array(['p w', 's k i l l s', 'o n l i n e', 'c l a s s'], dtype='<U11')

In [ ]:
'''7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.'''
arr7=np.array([[2,3,4],[5,6,7]])
arr8=np.array([[1,3,6],[2,9,8]])
arr7+arr8
arr7-arr8
arr7*arr8
arr7/arr8


array([[2.        , 1.        , 0.66666667],
       [2.5       , 0.66666667, 0.875     ]])

In [ ]:
"8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements."
arr8=np.identity(5)
np.diag(arr8)

array([1., 1., 1., 1., 1.])

In [ ]:
'''9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.'''
arr9=np.random.randint(0,1000,100)
isprime=0
for i in arr9:
    if i>1:
        isprime=0
        for j in range(2,(i)):
          if i%j==0:
             isprime=5
             break

    if isprime==0:
      print(i)


89
457
661
139
907
389
569
821
433
571
7
59
3
467
109
47
773
967
839


In [ ]:
'''10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.'''
arr10=np.array([34,18,34,28,18,23,33,45,42,42,19,29,37,28,11,41,39,25,22,34,18,34,28,18,23,33,45,42])
np.random.shuffle(arr10)
r=arr10.reshape(4,7)
print(r)
np.mean(r,axis=1)

[[39 42 45 25 34 28 33]
 [41 28 18 42 23 34 18]
 [34 18 23 11 33 29 37]
 [34 28 45 42 22 19 18]]


array([35.14285714, 29.14285714, 26.42857143, 29.71428571])